### ISSUE TITLE
Problem running BACKWARD run of COSMOS

### ISSUE THREAD

**Issue by samuelbunga** [saezlab/COSMOS#7]
Hi,
I am trying to run COSMOS tutorial and installed the cosmos v0.1[](https://github.com/saezlab/COSMOS/releases/tag/v0.1).
While trying to run the command `preprocess_COSMOS_metabolism_to_signaling`, I'm getting this error message 
`Writing constraints...
Error in write_constraints_6(variables = variables, dataMatrix = dataMatrix,  : 
  object 'cc1' not found`

Could you please help me fix it? 

Thanks in advance.

**Comment by gabora** [comment]
Hi, 
this is a known issue of CARNIVAL and the bug was fixed on our GitHub repo. 
Could you please install CARNIVAL from here:  [Link](https://github.com/saezlab/CARNIVAL)
`devtools::install_github("saezlab/CARNIVAL")`
